#!/usr/bin/env python

import random
import sys


def help():
    print(
        "Usage: rng <amount: int> <min_bound: float = -1.0> <max_bound: float = 1.0> <decimals: int = 2>"
    )


def main():
    if len(sys.argv) < 2:
        help()
        sys.exit(1)

    try:
        amount = int(sys.argv[1])
        min_bound = float(sys.argv[2]) if len(sys.argv) > 2 else -1.0
        max_bound = float(sys.argv[3]) if len(sys.argv) > 3 else 1.0
        decimals = int(sys.argv[4]) if len(sys.argv) > 4 else 2

        numbers = [random.uniform(min_bound, max_bound) for _ in range(amount)]
        numbers = [round(number, decimals) for number in numbers]
        if decimals == 0:
            numbers = list(map(int, numbers))
        print(" ".join(map(str, numbers)))

    except Exception as e:
        print(e)
        help()
        sys.exit(1)


if __name__ == "__main__":
    main()
