#!/usr/bin/env bash

case_number=$1

response=$(curl -s "https://egov.uscis.gov/csol-api/case-statuses/$case_number" --compressed -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://egov.uscis.gov/' -H 'Content-Type: application/json')

echo $response | jq
